export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";

export const FILTER_DONE_TASKS = "COMPLETE_TASKS";
export const FILTER_UNDONE_TASKS = "FILTER_UNDONE_TASKS";
export const FILTER_ALL_TASKS = "FILTER_ALL_TASKS";
